$:
  vscode:
    - docker:
        image: docker.cnb.cool/xmzzuzhi/cnb-docker/ipynb:cuda12.8.1-pytorch2.4.1-prod
      imports:
        - https://cnb.cool/XMZZUZHI/key/-/blob/main/ipynb.yml
      runner:
        cpus: 32
      services:
        - vscode
        - docker
      stages:
        - name: 授予install_gpg_keys.sh权限
          script:
            - chmod +x /workspace/install_gpg_keys.sh
            
        - name: 安装iflow
          script:
            - npm i -g @iflow-ai/iflow-cli@latest
            - echo "iflow安装完成"

        - name: 安装sudo更新APT源
          script:
            - apt-get update
            - apt-get install -y sudo lsof net-tools
            - echo "依赖完成"
            
        - name: 安装Git LFS
          script:
            - sudo apt-get install -y git-lfs
            - git lfs install
            - echo "Git LFS安装完成"
  push:
    - services:
        - docker
      imports:
        - https://cnb.cool/XMZZUZHI/key/-/blob/main/Github.yml
      stages:
        - name: 同步到GitHub
          image: tencentcom/git-sync 
          settings:
            target_url: https://github.com/xiaomizhoubaobei/ipynb.git
            auth_type: https
            username: ${GIT_USERNAME} 
            password: ${GIT_ACCESS_TOKEN}
            branch: main
            git_user: ${GIT_USERNAME}
            git_email: ${GIT_EMAIL}